Modify `side_condition` results to be only `false` or `true` in Proof Hints
runtimeverification/llvm-backend pull request #1023
Opened 2024-04-08 22:25 UTC by Robertorosmaninho

2024-04-09 09:03 UTC, Baltoli requested changes
Some questions and changes. Please also make sure that you accompany any PRs you open with a body that explains the context for the changes. This is important for reviewing _now_, as well as in the future when we look back at historical changes to try and understand them.

2024-04-09 18:50 UTC, Robertorosmaninho commented on runtime/util/ConfigurationSerializer.cpp
> +void write_bool_to_file(FILE *file, void *subject) {
Good point! I've just done it!

2024-04-09 18:50 UTC, Robertorosmaninho commented on lib/codegen/ProofEvent.cpp
> +    term = b.CreatePointerCast(term, i8_ptr_ty);
Dwight pointed out to me that this is always a boolean: [see](https://github.com/runtimeverification/llvm-backend/blob/2c4eb2f0e80913a49c827a9821c51f9d133e7362/matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala#L773)!

2024-04-09 18:50 UTC, Robertorosmaninho commented on include/kllvm/binary/ProofTraceParser.h
> +  bool result_{false};
Yes, that makes sense. I'm choosing to make `result` as a mandatory argument then.

2024-04-09 18:50 UTC, Robertorosmaninho commented on include/kllvm/binary/ProofTraceParser.h
>    sptr<kore_pattern> kore_pattern_{};
Yes! Thanks for noticing that! I removed it everywhere here, but we'll need to modify `pyk` as well since I had to modify the bindings!

2024-04-09 21:28 UTC, theo25 approved these changes
This looks good to me but I think you should wait for Bruce to review your latest changes before you merge.

2024-04-10 13:05 UTC, Baltoli approved these changes
One minor comment, otherwise looks good!

2024-04-10 13:05 UTC, Baltoli commented on include/kllvm/binary/ProofTraceParser.h
> +  void set_result(bool result) { result_ = result; }
This is dead code now.
```suggestion
```

2024-04-10 13:57 UTC, Robertorosmaninho commented on include/kllvm/binary/ProofTraceParser.h
> +  void set_result(bool result) { result_ = result; }
Good point! Thank you!

2024-04-10 16:43 UTC, merged