INSTALL: Remove libunwind from MacOS dependencies
runtimeverification/llvm-backend pull request #1114
Opened 2024-07-22 20:14 UTC by stevenmeker

libunwind is not available from Brew, and we don't need it anyway because MacOS LLVM doesn't need it.

2024-07-22 20:18 UTC, Baltoli approved these changes

2024-07-22 20:19 UTC, Baltoli commented
@stevenmeker can you please rebase this PR against the `develop` branch?

2024-07-22 20:19 UTC, Baltoli requested changes
Needs rebased against `develop` and the versioning commits removed.

2024-07-22 22:30 UTC, stevenmeker commented
rebase done

2024-07-23 08:23 UTC, Baltoli approved these changes
Thanks @stevenmeker!

2024-07-23 08:28 UTC, merged