Introducing new `llvm_pattern_matching_failure_event` to Proof Events
runtimeverification/llvm-backend pull request #1134
Opened 2024-08-13 18:10 UTC by Robertorosmaninho

This PR introduces a new function event called `llvm_pattern_matching_failure_event`, which is identified by the `pattern_matching_failure_sentinel`. This new event flags to the user that an attempt to apply a rule failed in pattern matching its constructor; therefore, no further simplification can be done at this point.

2024-08-15 18:53 UTC, Robertorosmaninho commented
We still need to bump the version from 11 to 12, but this will be terrible to review after modifying all the tests, so I'll bump it as soon as I have your approval in the main implementation.

2024-08-16 19:18 UTC, dwightguth approved these changes

2024-08-16 23:51 UTC, theo25 requested changes
Looks good, but please take care of the one comment that I left.

2024-08-16 23:51 UTC, theo25 commented on docs/proof-trace.md
> +pattern_matching_failure ::= WORD(0x44) function_name
This needs to appear in the right hand side of some production, most likely the `argument` and `event` productions.

2024-08-20 19:45 UTC, theo25 approved these changes

2024-08-20 20:26 UTC, merged