Un-nest proof hint events for arguments of functions/hooks
runtimeverification/llvm-backend pull request #1140
Opened 2024-08-28 23:44 UTC by theo25

The events that correspond to evaluation of arguments of functions and hooks are currently nested inside the corresponding function/hook event. There is no need for that and it creates various complications in the processing of the proof hint trace. For this reason, this PR un-nests those events so that they appear before their corresponding function/hook event.

2024-08-29 13:42 UTC, Robertorosmaninho approved these changes
LGTM.
Should we update the [proof-trace.md](https://github.com/runtimeverification/llvm-backend/blob/master/docs/proof-trace.md) with new info?

2024-08-29 18:29 UTC, theo25 commented
@Robertorosmaninho I added a commit with the update and a simplification to the parser logic. Thanks for pointing that out!

2024-08-29 20:31 UTC, Robertorosmaninho commented
> @Robertorosmaninho I added a commit with the update and a simplification to the parser logic. Thanks for pointing that out!

Wow! That was a huge simplification! Thanks!

2024-08-30 20:26 UTC, gtrepta requested changes
LGTM, but I think I found a bug. Please fix it and then I can approve.

2024-08-30 20:26 UTC, gtrepta commented on lib/codegen/CreateTerm.cpp
>      }
`i` isn't being incremented here.

2024-08-30 21:27 UTC, theo25 commented on lib/codegen/CreateTerm.cpp
>      }
Good catch! Fixed

2024-09-01 04:39 UTC, gtrepta approved these changes

2024-09-03 19:02 UTC, merged