Improve `llvm-kompile` interface (part 1)
runtimeverification/llvm-backend pull request #558
Opened 2022-09-09 12:37 UTC by Baltoli

`llvm-kompile` isn't a friendly script to use; it can't pass through options like `-v` and `-save-temps` to its callees, and its documentation is out of date.

This PR makes a start to improving its interface, by duplicating its functionality into a new `llvm-kompilex` script that has nicer option parsing and documentation. We need to have both scripts around for a time so that the frontend can be tested with the new script, after which point the old one can be deleted (cf. the `kprovex` migration). An audit of downstream repos will be required here.

The reason for the two-step change is that we need to separate the clang flags (e.g. `-g`, `-O0`) from the script flags (`-v` etc.). We do this with a `--` separator, which creates a small incompatibility in the script syntax.

2022-09-20 17:22 UTC, dwightguth requested changes
This looks really good but I did have one suggestion to make

2022-09-20 17:22 UTC, dwightguth commented on bin/llvm-kompilex
> +    --)
I feel like in order to follow standard practices for scripts like this, this should probably be optional.

2022-09-22 15:29 UTC, ehildenb commented
Options we should make sure that all scripts support moving forward:

- `--profile`: Coarse-grained (process-level) profiling.
- `--debug`: Stack traces, heap dumps, etc...
- `--verbose`: Extra information about what's going on.

2022-09-22 19:59 UTC, dwightguth approved these changes

2022-09-22 22:46 UTC, merged