Fix for priorities not being checked for map choices
runtimeverification/llvm-backend pull request #587
Opened 2022-10-14 17:03 UTC by Baltoli

This is the backend fix for https://github.com/runtimeverification/llvm-backend/issues/539; I'll follow it up by adding a test case with Manasvi's code.

2022-10-14 18:55 UTC, dwightguth commented
This code is finicky enough I'd actually like this test added to the backend integration test suite.

2022-10-14 19:44 UTC, Baltoli commented
Added @dwightguth - you can see the correct bar, foo ordering in the KORE output pretty easily.

2022-10-18 15:01 UTC, dwightguth requested changes

2022-10-18 15:01 UTC, dwightguth commented on matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/Pattern.scala
> +      case (HasKey(_, _, _), Some(_)) => clause.action.priority <= maxPriority
I just noticed that this case isn't checking that a choice is occurring before checking the priority. I'm surprised we haven't found any failures running the test suites due to this, but we should still address it.

2022-11-07 16:44 UTC, dwightguth approved these changes

2022-11-07 18:29 UTC, merged