Introducing llvm backend support for `--execute-to-branch` feature
runtimeverification/llvm-backend pull request #756
Opened 2023-05-10 18:11 UTC by Robertorosmaninho

This PR introduces a new feature to the llvm-backend: the option to stop the search execution when a branch is found.
This feature is already supported by the Haskell-backend `kore-exec` within the flange  `--execute-to-branch`. The name and the use of the flag are the same used on Haskell-backend to ease the adoption by users.

To use it: 
```
module TEST
  imports BOOL

  syntax Foo ::= "a" | "b" | "c" | "d" | "e"

  rule a => b
  rule b => c
  rule c => d
  rule c => e

endmodule
```
```Bash
kompile --backend llvm --enable-search test.k
krun -cPGM='a' --search --execute-to-branch 
```

Expected output:
```
{
  Result:GeneratedTopCell
#Equals
  <k>
    c ~> .
  </k>
}
```

Fixes #752

2023-05-11 09:25 UTC, Baltoli commented on test/search/search-execute-to-branch.kore
> +*/
Nice one - this will be really helpful to @dwightguth!

2023-05-11 09:25 UTC, Baltoli approved these changes

2023-05-11 20:40 UTC, dwightguth requested changes
Please check in the k file the kore definition was generated from

2023-05-11 20:40 UTC, dwightguth requested changes
Please check in the k file the kore definition was generated from

2023-05-12 17:21 UTC, dwightguth approved these changes

2023-05-15 17:24 UTC, merged