Flags to turn on/off proof hint instrumenation and output
runtimeverification/llvm-backend pull request #879
Opened 2023-11-10 23:42 UTC by theo25

This PR adds two flags to our scripts to turn the proof hint instrumentation and output on and off:
- a flag `--proof-hint-instrumentation` is added to the `llvm-kompile` script. When the flag is passed the generated llvm code is instrumented with proof hint generation code.
- a flag `--proof-hints` is added to the `llvm-krun` script. When the flag is passed to an instrumented interpreter binary, the binary will output proof hints.

2023-11-12 17:49 UTC, gtrepta reviewed
Maybe it would be simpler for `ProofEvent` to read the ProofHintInstrumentation flag and turn its code emitting functions into effective no-ops if it's false? That way nothing needs to be changed across the multiple places it gets used.

2023-11-13 13:54 UTC, Baltoli approved these changes

2023-11-13 13:54 UTC, Baltoli commented on lib/codegen/CreateTerm.cpp
> +    llvm::cl::cat(CodegenCat));
Yep, I basically agree with Guy's suggestion - let's push this option into the `ProofEvent` class. Otherwise the plumbing code etc. all looks good!

2023-11-13 13:56 UTC, Baltoli requested changes
One organisational comment as Guy notes also; otherwise all good!

2023-11-13 17:30 UTC, gtrepta requested changes
You'll need to add a lit command to kompile with the proof instrumentation and have `tests/defn/imp-proof.kore` use it

https://github.com/runtimeverification/llvm-backend/blob/0e24009e09ac3f96b796a9bb11d078dc3b49fdc3/test/lit.cfg.py#L80-L87

2023-11-13 19:19 UTC, Baltoli approved these changes
Looks good @theo25; feel free to merge!

2023-11-14 09:21 UTC, Baltoli commented
@gtrepta you'll need to dismiss your review here if you're happy with the state of the PR

2023-11-14 16:29 UTC, gtrepta approved these changes

2023-11-14 16:43 UTC, merged