Add term simplification to Python bindings
runtimeverification/llvm-backend pull request #897
Opened 2023-11-21 12:06 UTC by Baltoli

2023-11-22 12:45 UTC, Baltoli commented
I have also tested the booster's integration tests with this change applied and there is no breakage to the C bindings.

2023-11-22 15:10 UTC, tothtamas28 reviewed
Looks good in terms of functionality.

Python tests: https://github.com/runtimeverification/pyk/pull/736

2023-11-27 14:25 UTC, dwightguth requested changes
It's very difficult to follow these changes because they are a mix of a refactoring that moves a lot of code around, and new features. I'm concerned that despite my best efforts, I still wasn't really able to determine what code was "new" and review it effectively.

I think you need to refactor the history of this PR to more obviously break it into two components: the moving around of existing code, and the addition of new code.

2023-11-28 15:41 UTC, Baltoli commented on bindings/c/lib.cpp
> +  inj->ptr_ = kllvm::bindings::make_injection(term->ptr_, from->ptr_, to->ptr_);
@dwightguth As an example of how to look at the changes in this diff, the `kllvm::bindings::make_injection` function contains code that is _equivalent_ to the C on the LHS here, but using the underlying C++ structures directly. All the changes in this commit are of that form.

2023-11-28 15:42 UTC, Baltoli commented on bindings/core/src/core.cpp
> +  return inj;
The restated C++ code from my other comment is here.

2023-11-28 18:50 UTC, dwightguth approved these changes

2023-11-28 20:42 UTC, merged