Make bytes objects copy-on-write
runtimeverification/llvm-backend pull request #950
Opened 2024-01-12 16:03 UTC by Baltoli

2024-01-15 22:22 UTC, Scott-Guest requested changes
The overall approach LGTM, but we currently overlook some aliasing

2024-01-15 22:26 UTC, Scott-Guest commented on lib/codegen/CopyOnWrite.cpp
> +        sort->getName() == "SortBytes") {
On a similar note, you can probably do something sneaky with `String2Token` and `Token2String` because those hooks don't copy their args

2024-01-16 09:37 UTC, Baltoli commented on lib/codegen/CopyOnWrite.cpp
> +        sort->getName() == "SortBytes") {
Good catches, thanks Scott - I think we can pretty easily address those points:
* Look up the sort in the definition's sort table to see if it's hooked to `BYTES.Bytes`
* Build the partial order defined by the definition's subsort axioms when we load a definition; we then expand the check above to include the above hooked sorts and anything that's a proper superset thereof.

For the token hooks, I will see if I can cook up an example that breaks things as well.

2024-01-16 09:38 UTC, Baltoli commented on lib/codegen/CreateTerm.cpp
> +  }
Ah I had meant to comment this; it took me a while to figure out what was going on but I didn't go back to explain myself

2024-01-16 14:54 UTC, Baltoli commented on lib/codegen/CopyOnWrite.cpp
> +        sort->getName() == "SortBytes") {
#951 and #952 are prerequisites to implementing the fixes here

2024-01-18 12:34 UTC, Baltoli commented
The approach in this PR needs a bit more work and evaluation to fix Scott's failing test case above, as well as one suggested by @dwightguth.

2024-01-25 14:27 UTC, Baltoli commented
I think on balance looking at the final version of this change, it's very unlikely that we'll be able to implement the required semantics in a way that's both sound and performant.

2024-01-25 15:55 UTC, closed without merging